apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
spec:
  containers:
  - name: mysql
    image: mysql
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: xandersms
      - name: MYSQL_USER
        value: xander
      - name: MYSQL_PASSWORD
        value: xander
  volumes:
    - name: mysql-data
      persistentVolumeClaim:
        claimName: pvc